### PR TITLE
Added option to narrate some parts of dialog text

### PR DESCRIPTION
**Pull request by BelegCufea**
Hello,

I noticed that you made some changes to the TTS module to use separate voices for male and female characters (not just the two lines I mentioned in the comments).

I was wondering if we could have a third voice to be used as a narrator to read specific texts, such as NPC titles, quest names, objectives, and text enclosed in <> brackets.

I’ve put together some code to achieve this. I've tested it a bit and it seems to work fine, but it definitely needs more testing.

I added comments in the code (only in TTS.lua), but I'm unsure if it's clear enough even with those comments.

If you think this feature is unnecessary, that’s perfectly fine. I love your addon as it is.

Have a nice day.

### CODE REVIEW

**Comment by Peterodox** [comment]
Wow! Thanks for contributing 😄 

I'm currently investigating some experience-breaking issues, and TWW's official release date is  2 days later when I'll be on a trip for a few days. So please excuse me I don't wish to add any new features before at least next weekend.

Your proposed feature has not been asked for before, but I see no harm in adding it. I dislike showing an overwhelming wall of options, but we could hide it behind an advanced setting.

**Comment by BelegCufea** [comment]
Yup, I hate that wall of options as well.

As a poor bloke without early access pre-paid, I’ve got nothing to do but to bother serious addon authors with silly suggestions :-) Take your time, or feel free to toss it in the trash (where it may belong).

Have a great day and good luck hunting down those errors.

By the way, I’ve encountered an error a few times when turning in a quest and immediately picking up a new one from the same NPC—an empty dialog box appears. Maybe it is connected to #38. It’s not a big deal, as I can just close the dialog and interact with the NPC again. Also, your latest fix for not needing to step away from the NPC to talk to them again works flawlessly.

**Comment by BelegCufea** [comment]
FYI. This implementation also fixes issues like this (from Curse comment section):

image

I had those before as well. But first I made a plugin for [Quest TTS](https://www.curseforge.com/wow/addons/questtts) to work with Dialogue UI and now I am using this PR. Not a single instance of the above issues encountered since.

**Comment by Peterodox** [comment]
It's time for me to see what you've been cooking 😆

**Comment by BelegCufea** [comment]
:-) Just please survive my awful code edits in good health.

**Comment by Peterodox** [comment]
I didn't make many changes because it works pretty well :)

I'm still pondering if "Skip Recently Read Texts" should be a valid option. I  understand that sometimes you exit and return to the same dialogue, so you don't want it to play again. But it makes me feel like Auto Reading isn't working, and the player may have forgotten they enabled this option.

**Comment by BelegCufea** [comment]
It is usually for the gossip part of the NPC so you don't hear it like 10 times when there are more options. Sometimes the gossip is really long.

**Comment by BelegCufea** [comment]
Maybe use it just for gossip changing line 153 in TTS.lua from

```lua
if self.forceRead or (TTS_SKIP_RECENT and TTS_AUTO_PLAY) then
```

to something like this?

```lua
if self.forceRead or (TTS_SKIP_RECENT and TTS_AUTO_PLAY and not content.title) then
```

**Comment by BelegCufea** [comment]
Or better yet what about to show an overlay when dialog was already read. Something like this:

When creating TTSButton (just picked one of your icons as example):
```lua
...
        b.Wave1:Hide();
        b.Wave2:Hide();
        b.Wave3:Hide();

        b.Read = b:CreateTexture(nil, "OVERLAY");
        b.Read:SetSize(0.75*ICON_SIZE, 0.75*ICON_SIZE);
        b.Read:SetPoint("TOPLEFT", b, "TOPLEFT", -2, 2);
        b.Read:SetTexture("Interface/AddOns/DialogueUI/Art/Icons/Gossip.png");
        b.Read:Hide();
...
```

and then Show/Hide it:
```lua
...
            -- if found and player didn't press the play button manually then return
            if found and not self.forceRead then
                TTSButton.Read:Show();
                return
            end
        end
        self.forceRead = nil;
    end
    TTSButton.Read:Hide();
    --if player wants to use narrator and the current voice is not narrator, queue different parts of quest for reading
    if TTS_USE_NARRATOR and voiceID ~= voiceIDNarrator then
...
```

Could do full PR, if necessery.

**Pull request merged**
